// #pragma once

#define DEVICE_ID "GPS_TRACKER_1"

#define GPS_LOG_PERIOD_SEC 3

#define GPS_RX_PIN D7
#define GPS_TX_PIN D6
#define GSM_RX_PIN D5
#define GSM_TX_PIN D0

#define BASE_LOCATION_TPC "/HOME_AUTOMATION/STREET/CAR"

#define GPS_TPC "/HOME_AUTOMATION/STREET/CAR/GPS"


